title: "Khuong Quynh Long"
subtitle: "Khuong Quynh Long, 2021"
description: "This is the repository for my Master in Statistics and Data Science program at Hasselt University, Belgium"
email: quynhlong.khuong@student.uhasselt.be
permalink: "/stories/:title"
url: "https://github.com/khuongquynhlong/Biostat"
relative_permalinks: false
theme: jekyll-theme-architect
show_downloads: true