title: "Master in Statistics and Data Science"
description: "This is my personal repository for my homework and projects of my Master’s program at Uhasselt, Belgium"
permalink: "/stories/:title"
url: https://github.com/khuongquynhlong/Biostat
relative_permalinks: false
theme: jekyll-theme-architect
